### PR TITLE
Update userController.js

### PR DESCRIPTION
**Pull request by MuhamadCheaito**

### CODE REVIEW

**Comment by fdhhhdjd** [comment]
where is wrong?

**Comment by MuhamadCheaito** [comment]
Nothing special, I was running the app and suddenly ran out an error and the error was that you typed er instead of err in the loginAdmin route.

**Comment by fdhhhdjd** [comment]
ok thank pro

**Comment by fdhhhdjd** [comment]
The temporary backend is already great, if I need any more functionality, I'll see it before merging.

**Comment by MuhamadCheaito** [comment]
> The temporary backend is already great, if I need any more functionality, I'll see it before merging.

Yeah It's pretty good I like it, good luck with that man :)

**Pull request merged**
